# Citizen Scientist Roles and Motivations

This pillar involves citizen scientists primarily as collectors and validators of mosquito data. Citizen scientists form a massive network of sensors with the goal of expanding the geographic coverage of monitoring programs without the costs associated with traditional surveillance methods. Citizen scientists participate in data validation by reviewing others’ reports, using practical identification tools and relying on both validator proficiency scores (each citizen scientist’s proficiency in the validation process) and redundancy (multiple citizen scientists reviewing each report) to reduce errors. Experts are also involved in the validation stage to improve accuracy and provide a point of comparison for generating the citizen scientists’ proficiency scores. The analysis is done by experts as well, but mechanisms for better involving citizen scientists as experts will be explored in the future.

Citizen scientists participating in this Pillar are likely to have a variety of motivations depending on local conditions and socio-demographic factors. There has yet to be a systematic study of participant motivations in the existing GMAC projects but a number of conclusions can be drawn from anecdotal evidence coming out of these projects.

The citizen scientists who participate in Mosquito Alert in areas of Spain with high mosquito prevalence appear to be motivated primarily by the annoyance of mosquitoes and a desire to “do something” in response to being bitten. Many are also motivated by concerns about the spread of mosquito-borne diseases, although this is more of an abstract concern in Spain as autochthonous transmission of such diseases has not yet been detected. It is likely that participants in areas of Spain with low mosquito prevalence are motivated more by this latter concern – by the desire to act as sentinels against the arrival of a potentially dangerous species. In addition, it is likely that many participate due to the more traditional citizen science motivations of curiosity and interest in science.

These motivations are likely to vary in other areas of the word and to shift depending on season, local mosquito distribution and biting patterns, changing disease risks, and experiences with the toolkit or with other citizen science projects. Understanding how this variation and shifting occurs, how different motivations may blend into one another is important both for ensuring sufficient participation levels and for correcting sampling bias. In addition, it should be stressed that the primary motivation of annoyance in high-prevalence areas makes mosquito-focused citizen science projects somewhat unique: At least in these areas, the target of the project itself provides participants with a continuous reminder to act. 
