# Ethics

Ethical considerations take on heightened relevance when citizen scientists are involved in disease-vector monitoring – and particularly when they are in the vicinity of organisms that could potentially carry dangerous diseases. These concerns fall into two categories: health risks and privacy. In addressing these, autonomy must also be used as a guiding value.

The risk of participants’ health being harmed by being bitten by the mosquitoes they are reporting is the most obvious concern in this pillar. Although people in high-prevalence areas are likely exposed to mosquito biting regardless of participation, projects falling within this pillar must be fully transparent about the risks and must be careful not to encourage increased risk-taking. Indeed, projects should ideally help participants reduce their risks, not only by harnessing their reports to provide better control, but also by teaching them how best to avoid bites and remove mosquito breeding sites.

Privacy concerns also take on new dimensions when disease vectors are involved. Participants’ locations, while inherent in reporting and important for correcting sampling bias, can reveal a wide variety of information that individuals may prefer to keep private – including disease risk. It is critical that people be fully informed about the location information they are revealing when they consent to participation and that they have control over how much information they share. The Mosquito Alert project, for example, relies on background location tracking to correct sampling bias, but it explains this to participants when they register and it allows them to turn the feature off or on at any time.  It is also important to limit the amount of information collected: The Mosquito Alert app, for instance, collects only 5 background locations per day from each participant who has not opted out, and it obscures these locations by placing them in predefined cells of approximately 10 sq. kilometers and sharing only the cell identifiers with the central server. The iNaturalist app collects no background tracking information and it gives participants the option of obscuring report locations on the public webmap.
