# Data Collection

Data collection for this pillar involves, at a minimum, citizen scientists reporting adult mosquitoes as they observe them. This may be as simple as providing information about the date, time, and location of observations. Of greater use, however, are reports that (1) are limited to targeted species, (2) include the observer’s taxonomic identification, (3) include the observer’s description, through a brief questionnaire, of key features necessary for identification, and (4) are accompanied by a photograph of the mosquito. The last two pieces of information are particularly important, as they allow for subsequent data validation by other citizen scientists or experts. At the same time, not every report needs to include all this information to have value: As long as complete information is included in some reports, they can be used to estimate individual participants’ proficiency, which can then serve as a basis for assessing the reliability of their other reports.

The most efficient mechanism for transmitting reports is currently through smart phones or other mobile devices. This is the approach taken by all of the existing projects in this pillar and it allows for near real-time collecting and analysis of data. The applications used for transmitting reports also serve as tools to help participants identify mosquitoes and take protective measures, to validate others’ reports, and to view global project information and otherwise interact with project managers. At the same time, other reporting mechanisms, including SMS or even simply paper and regular mail, are clearly possible and might be explored for use in areas with low smartphone penetration.

