# Data Presentation and Use

## End-users and requirements

The pillar and the data generated can be of interest to 4 main types of end-users: the general public, public health managers, educators, and academics. Each targeted audience requires a different mode of data presentation and use.

## Data presentation to public and specific end users

### General Public:

* General informative contents on main web and social networks, and also through app notifications (entomology, public health, distribution, prevention measures, etc.). Content should be distributed in a way that maximizes potential reuse while also protecting participants’ privacy and respecting their preferences. Where possible, this should be done by placing it in the public domain with the Creative Commons “no rights reserved” mark (CC0). Where attribution is required, the Creative Commons Attribution License (CC BY) is recommended. This can be combined with privacy protections by listing the author as an “anonymous” citizen scientist, as is done for participant photos shared in Mosquito Alert. Another option is to give participants the choice of multiple licenses and let them choose how to list themselves, as is done in iNaturalist. 
* Annual reports (freely downloadable from web in pdf): Summary of the project current results and achievements within the year, encompassing science, mosquito management, education and communication.
* Interactive Map: A public map with all the reports and validations, with filters (temporal and spatial) and from which anyone can directly download data in CSV, KML, and other formats. This can be done directly on project websites and/or by publishing the data on GBIG.org, which provides a web map, download options, dataset metrics, a download-DOI, and statistics on downloads and citations. As explained in the first bullet-point above, content should be distributed in a way that maximizes potential reuse while also protecting participants’ privacy and respecting their preferences.
* Direct access to data download may also be provided to the public separately from the map (for example, as is done in iNaturalist and Mosquito Alert). As explained in the first bullet-point above, content should be distributed in a way that maximizes potential reuse while also protecting participants’ privacy and respecting their preferences.

### Public Health Managers: 

* “Enrollment Kit” for Managers: An open and downloadable document with all the necessary information for stakeholders surveilling and controlling mosquito populations to use the mosquito alert platform on their own benefit. From the most simple type of information exploitation to more complex and committed ones.
* Private Portal: A digital platform with a private account where managers can see real-time information by citizens (without even being expert-validated). Data classification is more exhaustive than in the public map. The interface includes a set of temporal and spatial filters to manipulate data, a system to write notes to single or groups of participants, and the possibility to incorporate private geo-located management information (water drain cartography, risk areas, epidemiologically relevant information, etc).
* Interactive Map: A public map with all the reports and validations, with filters (temporal and spatial) and from which anyone can directly download data in CSV, KML and other formats.  As explained above in the first bullet point under General Public, content should be distributed in a way that maximizes potential reuse while also protecting participants’ privacy and respecting their preferences.

### Educators:

* Educational contents in the form of Webquests or other digital formats, for teachers to use in the classroom. 
* Leaflets, power points, and other graphically designed materials for teachers to use in the classrooms 
* Interactive Map: A public map with all the reports and validations, with filters (temporal and spatial) and from which anyone can directly download data in  CSV, KML and other formats.  As explained above in the first bullet point under General Public, content should be distributed in a way that maximizes potential reuse while also protecting participants’ privacy and respecting their preferences.

### Academics:

* Interactive Map: A public map with all the reports and validations, with filters (temporal and spatial) and from which anyone can directly download data in  CSV, KML and other formats.  As explained above in the first bullet point under General Public, content should be distributed in a way that maximizes potential reuse while also protecting participants’ privacy and respecting their preferences.
* Daily data transfers to open access repository like zenodo.
* Make code freely available in a public repository like GitHub under an open source license like the GNU General Public License (GPL) or the MIT license.
* Data sharing through GBIF. (To get started with this, contact your national GBIF node or, in the absence of one, register as a GBIF publisher and find a partner.)

## Data use for vector management and research

There are a variety of options for facilitating data use by vector managers and researchers apart from the mechanisms for presentation and distribution described above. For example, iNaturalist allows anyone to create a project to aggregate any data at any level (for example, some set of vector species at a selected geographic location). Mosquito Alert cooperates directly with vector managers and other public stakeholders through various mechanisms. We draw on these in proposing the following models of cooperation.
 
*Cooperation type 1*: _I want to use Global Mosquito Alert's data for monitoring and control purposes._

We offer the following options:

* View data: view sightings of targeted mosquitoes and their breeding sites in your territory, filtering by sighting type and date (months and years).
* Share selected data: have you found one or more sightings of interest in your territory? A breeding site you were previously unaware of, for example? Share the information with those involved in monitoring and control activities in your territory (municipal personnel, pest control companies, town or city councils, etc.). 
* Export data in a report: export sightings from a map view, with all their details (photo, coordinates, etc.), in the form of a report. Share it with those involved in monitoring and control activities in your territory (municipal personnel, pest control companies, town or city councils, etc.). 
* Communicate with citizens via the app: tell us about your territory's monitoring and control activities. We can send app users in your town or city messages of your choosing via the notification system.
* Generate your own maps: create a hashtag (e.g. #LocalCouncil) for your territory's citizens and municipal personnel to include in the "Notes" section when they report sightings. It is possible to use a filter to export all the data corresponding to a hashtag from the public online map in the form of a list.

*Cooperation type  2*: _I want to carry out informative, educational or prevention activities or campaigns to combat targeted mosquitoes, (a) using Global Mosquito Alert's free resources or (b) arranging a face-to-face activity (education, rise awareness action)._

We offer you the tools and resources listed below, which will be available on Global Mosquito Alert's website, free of charge, for your own informative, educational or prevention activities or campaigns to combat tiger mosquitoes:

* Informative leaflet in different languages, to distribute online or print*. You can add your institution's logo using the version in .ppt format. If you need to adapt the leaflet further, please contact us.
* Global Mosquito Alert poster in different languages, to distribute online or print.
* Images and drawings of targeted mosquitoes and their breeding sites (see distribution licence in each case). Global Mosquito Alert images and logos.
* Extensive informative content, all up to date and revised by experts in scientific communication, covering entomology, public health, distribution, prevention measures, etc. Unless otherwise indicated, these may be reused under a Creative Commons licence (CC BY).
* Global Mosquito Alert's communication channels are available to you to give your campaign a boost online. Contact us to discuss ways of doing so.
* Web blog for brief communiqués or news items.
* Social media accounts (Twitter, Facebook, Weibo, WeChat).
* App notifications sent directly to the public participants.
* YouTube channel.

*Cooperation type 3*: _I want to establish a different type of cooperation or formalize cooperation through an agreement or protocol._

Formalizing cooperation entails many benefits for both parties. It is a way of establishing a joint plan, specifying each party's rights and obligations, and pursuing optimal results in relation to common and individual goals alike, so that cooperation pays greater dividends. It is also a way for an institution to become an official partner of Global Mosquito Alert and have access to the private managers portal and the app notification system from which managers can freely communicate with citizens their surveillance and control actions.

## Data Licensing

Data should be released with an open access license or placed in the public domain (CC0). The latter option is best for maximizing potential reuse, but there may be situations in which CC-BY (open access with attribution required) is preferable, Restrictions beyond CC-BY are best avoided, although there may be value in giving individual citizen scientists a choice of multiple license options for their individual reports (as is done, for example, by iNaturalist).

